version: "3"

services:
  app:
    build: .
    container_name: "api"
    command: sh -c "yarn sequelize db:migrate && yarn start"
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    depends_on:
      - database

  database:
    image: "postgres:alpine"
    container_name: database
    environment:
      POSTGRES_PASSWORD: 46693445
      POSTGRES_USER: postgres
      POSTGRES_DB: "lemoney_challenger"
    volumes:
      - /pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
